on: [push]

jobs:
    pipeline:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              # 1. Checkout the repository
              uses: actions/checkout@v3

            - name: Run main
              # 4. Run the program
              uses: cargo run

            - name: Check output
              # 5. Run output_check.sh
              run: ./scripts/output_check.sh
