# 1. Execute on push
on: [push]

jobs:
    pipeline:
        # 2. Run on latest Ubuntu version
        runs-on: ubuntu-latest

        steps:
            # 3. Checkout the repository
            - uses: actions/checkout@v3

            - name: Run with cargo
              # 4. Run the program
              run: cargo run

            - name: Check output with output_check.sh
              # 5. Run output_check.sh
              run: ./.github/workflows/scripts/output_check.sh
